(function(){
'use strict';
const API='https://df-extrusor-api.reck-cp9.workers.dev', TOKEN_KEY='df_secure_token_v2', DEVICE_KEY='df_licenseauth_device_v1', ACCESS_KEY='df_auto_access_credential_v1';
const previousFetch=window.fetch.bind(window);
function saved(){try{return String(localStorage.getItem(ACCESS_KEY)||'').trim()}catch(e){return''}}
function device(){let id='';try{id=String(localStorage.getItem(DEVICE_KEY)||'').trim()}catch(e){}if(!id){id=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);try{localStorage.setItem(DEVICE_KEY,id)}catch(e){}}return id}
function msg(t,ok){const e=document.getElementById('licenseMsg');if(e){e.textContent=t;e.className='licenseMsg '+(ok?'ok':'err')}}
function unlock(){try{if(typeof window.dfUnlocked==='function')window.dfUnlocked();else{const g=document.getElementById('licenseGate'),a=document.getElementById('appContent');if(g)g.style.display='none';if(a)a.style.display='block'}}catch(e){}}
function gate(){const g=document.getElementById('licenseGate'),a=document.getElementById('appContent');if(g)g.style.display='flex';if(a)a.style.display='none'}
async function request(path,body,timeout){const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout||8000);try{return await previousFetch(API+path,{method:'POST',headers:{'Content-Type':'application/json','X-DF-Device':device()},body:JSON.stringify(body),cache:'no-store',signal:c.signal})}finally{clearTimeout(tm)}}
function save(j){const token=String(j&&j.token||'').trim(),credential=String(j&&j.accessCredential||'').trim();if(!token||!credential)throw Error('Resposta de acesso incompleta.');sessionStorage.setItem(TOKEN_KEY,token);localStorage.setItem(ACCESS_KEY,credential)}
async function restore(){if(!saved())return false;unlock();try{const r=await request('/access/session',{credential:saved(),deviceId:device()},7000);let j={};try{j=await r.json()}catch(e){}if(r.ok&&j.ok!==false&&j.token){sessionStorage.setItem(TOKEN_KEY,String(j.token));return true}if([401,403,404,410].includes(r.status)){localStorage.removeItem(ACCESS_KEY);sessionStorage.removeItem(TOKEN_KEY);gate();return false}return true}catch(e){return true}}
function prepare(){const url=new URL(location.href),general=String(url.searchParams.get('acesso')||'').toLowerCase()==='geral';if(saved()){restore();return}if(!general)return;gate();const old=document.getElementById('licenseKey');if(old)old.style.display='none';const btn=document.getElementById('licenseBtn');if(!btn)return;let wrap=document.getElementById('dfAccessIdentityWrap');if(!wrap){wrap=document.createElement('div');wrap.id='dfAccessIdentityWrap';wrap.innerHTML='<input id="dfAccessIdentity" type="text" autocomplete="username" placeholder="Digite seu WhatsApp ou código" style="display:block;width:100%;box-sizing:border-box;min-height:52px;border:1px solid #475569;background:#111827;color:#fff;border-radius:12px;padding:12px 14px;font:600 16px system-ui;margin:12px 0">';btn.parentNode.insertBefore(wrap,btn)}btn.disabled=false;btn.textContent='ACESSAR';msg('Digite sua identificação para liberar este aparelho.',true);btn.onclick=async function(e){e.preventDefault();e.stopPropagation();const input=document.getElementById('dfAccessIdentity'),identity=String(input&&input.value||'').trim();if(!identity){msg('Digite sua identificação.',false);return}btn.disabled=true;btn.textContent='LIBERANDO ACESSO...';msg('Verificando sua identificação...',false);try{const r=await request('/access/identify',{identity,deviceId:device()},8000);let j={};try{j=await r.json()}catch(x){}if(!r.ok||j.ok===false)throw Error(j.error||('Falha no acesso ('+r.status+').'));save(j);url.searchParams.delete('acesso');history.replaceState(null,'',url.pathname+(url.search||'')+url.hash);msg('Acesso liberado. Entrando...',true);unlock()}catch(err){msg(err&&err.name==='AbortError'?'O servidor demorou para responder. Toque em TENTAR NOVAMENTE.':String(err.message||err),false);btn.disabled=false;btn.textContent='TENTAR NOVAMENTE'}}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',prepare,{once:true});else prepare();
})();