(function(){
  'use strict';
  const $=id=>document.getElementById(id);
  const num=v=>window.parseNum?window.parseNum(v):(parseFloat(String(v||'').replace(',','.'))||0);
  const get=id=>num($(id)?.value);
  const fmt=(v,d=2)=>Number(v).toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d});
  const rs=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const set=(id,t)=>{const e=$(id);if(e)e.textContent=t};
  let timer=null;
  function schedule(){clearTimeout(timer);timer=setTimeout(calc,170)}
  function densSacola(){const s=$('saDs');if(!s)return 0;return s.value==='manual'?get('saDm'):num(s.value)}
  async function sacolaData(){if(typeof window.dfCalc!=='function')return{};return await window.dfCalc('sacola',{largura:get('saL'),comprimento:get('saC'),micra:get('saM'),densidade:densSacola(),descontoPct:get('saDes'),quantidade:get('saQ')})}
  async function fillFromSacolas(force=false){const auto=$('cuAuto');if(!force&&auto&&!auto.checked)return;try{const d=await sacolaData();if($('cuPeso')&&d.pesoQuantidadeKg>0)$('cuPeso').value=fmt(d.pesoQuantidadeKg,3);if($('cuUnid')&&get('saQ')>0)$('cuUnid').value=fmt(get('saQ'),0);set('cuAutoInfo',d.pesoQuantidadeKg>0?'Puxado da aba Sacolas: '+fmt(d.pesoUnidade,2)+' g por sacola • '+fmt(get('saQ'),0)+' sacolas por rolo • '+fmt(d.pesoQuantidadeKg,3)+' kg por rolo':'Preencha a aba Sacolas ou digite manualmente abaixo.')}catch(e){set('cuAutoInfo','Não consegui puxar os dados da aba Sacolas.')}}
  async function calc(){if(typeof window.dfCalc!=='function')return;await fillFromSacolas(false);const peso=get('cuPeso'),unid=get('cuUnid'),custoKg=get('cuKg'),lucroPct=get('cuLucroPct'),qtdRolos=get('cuQtd')||1;const vendaKg=custoKg*(1+lucroPct/100);try{const r=await window.dfCalc('custo',{pesoKg:peso,custoKg,vendaKg,quantidade:qtdRolos});const custoRolo=Number(r.custoUnidade)||0,vendaRolo=Number(r.vendaUnidade)||0,lucroRolo=Number(r.lucroUnidade)||0,custoUnid=unid>0?custoRolo/unid:0,vendaUnid=unid>0?vendaRolo/unid:0;set('cuLucro','+'+fmt(lucroPct,2)+'% = '+(custoRolo?rs(Number(r.lucroTotal)||0):'—'));set('cuCustoRolo',custoRolo?rs(custoRolo):'—');set('cuVendaRolo',vendaRolo?rs(vendaRolo):'—');set('cuPrecoUnid',vendaUnid?rs(vendaUnid):'—');set('cuCustoUnid',custoUnid?rs(custoUnid):'—');set('cuLucroRolo',lucroRolo?rs(lucroRolo):'—');set('cuVendaTotal',r.vendaTotal?rs(r.vendaTotal):'—');set('cuCustoTotal',r.custoTotal?rs(r.custoTotal):'—');set('cuLucroTotal',r.lucroTotal?rs(r.lucroTotal):'—')}catch(e){console.error(e)}}
  function build(){const pg=$('pgCu');if(!pg||pg.dataset.dfCustoAuto==='1')return;pg.dataset.dfCustoAuto='1';pg.innerHTML='<div class="card"><span class="tag">Custo</span><h2>Custo e venda automático</h2><div class="hint">Puxa o peso do rolo e a quantidade de sacolas da aba Sacolas. Também permite digitar tudo manualmente.</div><button id="cuPull" class="calcBtn alt" type="button">PUXAR DADOS DA ABA SACOLAS</button><label style="display:flex;gap:9px;align-items:center;margin-top:12px"><input id="cuAuto" type="checkbox" checked style="width:auto"> Preencher automático pela aba Sacolas</label><div id="cuAutoInfo" class="smallNote">Preencha a aba Sacolas ou digite manualmente abaixo.</div><div class="grid"><div><label>Peso do rolo (kg)</label><input id="cuPeso" class="main" inputmode="decimal" placeholder="Ex.: 6"></div><div><label>Sacolas por rolo</label><input id="cuUnid" class="main" inputmode="numeric" placeholder="Ex.: 2000"></div><div><label>Custo do material por kg</label><input id="cuKg" class="main" inputmode="decimal" placeholder="Ex.: 7,50"></div><div><label>Lucro desejado (%)</label><input id="cuLucroPct" class="main" inputmode="decimal" placeholder="Ex.: 30"></div><div><label>Quantidade de rolos</label><input id="cuQtd" class="main" inputmode="numeric" placeholder="Ex.: 10"></div></div><div class="result"><span>LUCRO TOTAL ESTIMADO</span><b id="cuLucro">—</b></div><div class="kpi"><span>Custo por rolo</span><b id="cuCustoRolo">—</b></div><div class="kpi"><span>Preço de venda por rolo</span><b id="cuVendaRolo">—</b></div><div class="kpi"><span>Preço por unidade / sacola</span><b id="cuPrecoUnid">—</b></div><div class="kpi"><span>Custo por unidade / sacola</span><b id="cuCustoUnid">—</b></div><div class="kpi"><span>Lucro por rolo</span><b id="cuLucroRolo">—</b></div><div class="kpi"><span>Venda total</span><b id="cuVendaTotal">—</b></div><div class="kpi"><span>Custo total</span><b id="cuCustoTotal">—</b></div><div class="kpi"><span>Lucro total</span><b id="cuLucroTotal">—</b></div></div>';['cuPeso','cuUnid','cuKg','cuLucroPct','cuQtd','cuAuto'].forEach(id=>$(id)?.addEventListener('input',schedule));['cuPeso','cuUnid'].forEach(id=>$(id)?.addEventListener('input',()=>{if($('cuAuto'))$('cuAuto').checked=false;schedule()}));$('cuPull')?.addEventListener('click',async()=>{if($('cuAuto'))$('cuAuto').checked=true;await fillFromSacolas(true);schedule()});['saL','saC','saM','saQ','saDes','saDm','saDs'].forEach(id=>{const e=$(id);e?.addEventListener('input',schedule);e?.addEventListener('change',schedule)});window.calcCu=calc;fillFromSacolas(true).then(calc)}
  function init(){build()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,200));else setTimeout(init,200);
})();
