(() => {
  'use strict';
  const API='https://df-extrusor-api.reck-cp9.workers.dev';
  const LICENSE_KEY='df_licenseauth_license_v1';
  const DEVICE_KEY='df_licenseauth_device_v1';
  const TOKEN_KEY='df_secure_token_v2';
  const MAT_KEY='df_formula_materiais_v2';
  const FORM_KEY='df_formulacoes_v2';
  const DEV_KEY='df_formula_dev_v1';
  const ACCESS_KEY='df_auto_access_credential_v1';
  let token=sessionStorage.getItem(TOKEN_KEY)||'';
  let FO_ROWS=[];
  let LAST_EX={};
  let LAST_FO={};
  const timers=new Map();
  const calcControllers=new Map();

  function $(id){return document.getElementById(id)}
  function parseNum(v){let s=String(v??'').trim().replace(/\s/g,'');if(!s)return 0;if(s.includes(',')&&s.includes('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(',','.');const x=parseFloat(s);return Number.isFinite(x)?x:0}
  function n(id){const e=$(id);return parseNum(e?e.value:0)}
  function fmt(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toLocaleString('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—'}
  function rs(v){return 'R$ '+fmt(Number(v)||0,2)}
  function set(id,t){const e=$(id);if(e&&e.textContent!==String(t))e.textContent=t}
  function esc(t){return String(t||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
  function safeLower(t){return String(t||'').trim().toLocaleLowerCase('pt-BR')}
  function debounce(name,fn,ms=0){
    const pending=timers.get(name);
    if(pending){
      if(pending.kind==='frame')cancelAnimationFrame(pending.id);
      else clearTimeout(pending.id);
    }
    const run=()=>{timers.delete(name);fn()};
    if(ms>0)timers.set(name,{kind:'timer',id:setTimeout(run,ms)});
    else timers.set(name,{kind:'frame',id:requestAnimationFrame(run)});
  }

  function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);localStorage.setItem(DEVICE_KEY,id)}return id}
  function dfMsg(t,ok=false){const e=$('licenseMsg');if(!e)return;e.textContent=t;e.className='licenseMsg '+(ok?'ok':'err')}
  function dfLocked(){if($('licenseGate'))$('licenseGate').style.display='flex';if($('appContent'))$('appContent').style.display='none'}
  function dfUnlocked(){if($('licenseGate'))$('licenseGate').style.display='none';if($('appContent'))$('appContent').style.display='block'}

  async function rawPost(path,body,useToken=true,signal){const headers={'Content-Type':'application/json','X-DF-Device':deviceId()};if(useToken&&token)headers.Authorization='Bearer '+token;const r=await fetch(API+path,{method:'POST',headers,body:JSON.stringify(body),cache:'no-store',signal});let j={};try{j=await r.json()}catch(_){}if(!r.ok||j.ok===false){const e=new Error(j.error||('Erro HTTP '+r.status));e.status=r.status;throw e}return j}
  async function dfLicenseAuthLogin(key,silent=false){const k=String(key||'').trim();if(!k){dfMsg('Digite sua licença.');return false}const btn=$('licenseBtn');if(btn)btn.disabled=true;if(!silent)dfMsg('Verificando licença no LicenseAuth...');try{const j=await rawPost('/auth',{licenseKey:k,deviceId:deviceId()},false);token=j.token||'';if(!token)throw new Error('Servidor não retornou uma sessão válida.');sessionStorage.setItem(TOKEN_KEY,token);localStorage.setItem(LICENSE_KEY,k);dfMsg('Licença válida. Acesso liberado.',true);setTimeout(dfUnlocked,120);return true}catch(e){token='';sessionStorage.removeItem(TOKEN_KEY);localStorage.removeItem(LICENSE_KEY);dfLocked();dfMsg(e.message||'Não foi possível validar a licença.');return false}finally{if(btn)btn.disabled=false}}
  async function dfCalc(type,input){if(!window.DFLocalCalculations||typeof window.DFLocalCalculations.calculate!=='function')throw new Error('Motor local de cálculos indisponível.');return window.DFLocalCalculations.calculate(type,input||{})}
  function apiError(e){if(e&&e.name==='AbortError')return;console.error('DF API:',e)}

  function dens(prefix){const s=$(prefix+'Ds');return s&&s.value==='manual'?n(prefix+'Dm'):s?parseNum(s.value):0}
  function toggleManual(prefix){const s=$(prefix+'Ds'),box=$(prefix+'DmBox');if(box)box.style.display=s&&s.value==='manual'?'block':'none'}
  function pesoMetroIdeal(){return Number(LAST_EX.pesoIdeal)||0}

  async function calcEx(){toggleManual('ex');try{const r=await dfCalc('extrusao',{largura:n('exL'),micra:n('exM'),densidade:dens('ex'),pesoMedido:n('exP')});LAST_EX=r;set('exGm',fmt(r.pesoIdeal||0,2)+' g/m');set('exMr',r.micraReal?fmt(r.micraReal,2)+' µm':'0,00 µm');const st=$('exSt');if(st){if(r.micraReal&&n('exM')){const dif=Number(r.diferencaMicraPct)||0;st.textContent=(dif>=0?'+':'')+fmt(dif,2)+'% em relação à micra desejada';st.className='status '+(Math.abs(dif)<=2?'ok':dif>0?'warn':'bad')}else st.textContent=''}debounce('cor',calcCor,50)}catch(e){apiError(e)}}
  function deltaText(d,nome){return(d>0?'Aumentar ':d<0?'Diminuir ':'Manter ')+nome+(d?' em aproximadamente '+fmt(Math.abs(d),0)+' RPM':'')}
  async function calcCor(){const massa=n('exCorMasA'),pux=n('exCorPuxA'),ar=n('exCorArA');set('exCorArRef',ar>0?'Anel de ar atual: '+fmt(ar,0)+' RPM — ajustar somente se necessário para estabilidade e refrigeração do balão.':'—');try{const r=await dfCalc('correcao',{largura:n('exL'),micra:n('exM'),densidade:dens('ex'),pesoMedido:n('exP'),massa,puxador:pux,ar});const des=Number(r.pesoIdeal)||0,med=Number(r.pesoMedido)||0,dif=Number(r.diferencaPct)||0,msg=$('exCorMsg');if(des>0&&med>0){set('exCorDif',(dif>=0?'+':'')+fmt(dif,2)+'%');if(msg){if(Math.abs(dif)<=2){msg.textContent='O filme está dentro do peso desejado.';msg.className='status ok'}else if(dif>0){msg.textContent='O filme está mais pesado/grosso que o alvo.';msg.className='status warn'}else{msg.textContent='O filme está mais leve/fino que o alvo.';msg.className='status bad'}}}else{set('exCorDif','—');if(msg){msg.textContent='Informe acima largura, micra, densidade e peso medido de 1 metro.';msg.className='status warn'}}if(!(des>0&&med>0)){set('exCorPuxRes','—');set('exCorMasRes','—');set('exCorPuxDelta','Resultado automático depois de preencher os dados de cima.');set('exCorMasDelta','Resultado automático depois de preencher os dados de cima.');set('exCorMasMantem','');set('exCorPuxMantem','');return}if(r.puxadorRecomendado){set('exCorPuxRes','PUXADOR RECOMENDADO: '+fmt(r.puxadorRecomendado,0)+' RPM');const d=Number(r.deltaPuxador)||0,e=$('exCorPuxDelta');if(e){e.textContent=deltaText(d,'puxador');e.className='status '+(Math.abs(d)<=1?'ok':'warn')}set('exCorMasMantem',massa>0?'Motor de massa: mantém '+fmt(massa,0)+' RPM':'Motor de massa: informe o RPM atual para mostrar quanto mantém.')}else{set('exCorPuxRes','—');set('exCorPuxDelta','Digite o RPM atual do puxador.')}if(r.massaRecomendada){set('exCorMasRes','MOTOR DE MASSA RECOMENDADO: '+fmt(r.massaRecomendada,0)+' RPM');const d=Number(r.deltaMassa)||0,e=$('exCorMasDelta');if(e){e.textContent=deltaText(d,'motor de massa');e.className='status '+(Math.abs(d)<=1?'ok':'warn')}set('exCorPuxMantem',pux>0?'Puxador: mantém '+fmt(pux,0)+' RPM':'Puxador: informe o RPM atual para mostrar quanto mantém.')}else{set('exCorMasRes','—');set('exCorMasDelta','Digite o RPM atual do motor de massa.')}}catch(e){apiError(e)}}
  async function calcProd(){const perc=n('exProdPerc');set('exProdTitulo',perc?((perc>0?'AUMENTAR ':'DIMINUIR ')+fmt(Math.abs(perc),2)+'%'):'—');try{const r=await dfCalc('producao',{massa:n('exProdMas'),puxador:n('exProdPux'),ar:n('exProdAr'),percentual:perc});set('exProdMasRes',r.massaNova?fmt(r.massaNova,0)+' RPM':'—');set('exProdPuxRes',r.puxadorNovo?fmt(r.puxadorNovo,0)+' RPM':'—');set('exProdArRes',r.arNovo?fmt(r.arNovo,0)+' RPM':'—');if(r.massaNova)set('exProdMasDelta',deltaText(Number(r.massaNova)-n('exProdMas'),'motor de massa'));if(r.puxadorNovo)set('exProdPuxDelta',deltaText(Number(r.puxadorNovo)-n('exProdPux'),'puxador'));if(r.arNovo)set('exProdArDelta','Referência inicial do ar: ajustar no balão.');set('exRelAtual',r.relacaoAtual?fmt(r.relacaoAtual,3):'—');set('exRelNova',r.relacaoNova?fmt(r.relacaoNova,3):'—');set('exRelMsg',r.relacaoAtual?'Relação mantida para preservar a micra próxima.':'')}catch(e){apiError(e)}}
  async function calcSa(){toggleManual('sa');try{const r=await dfCalc('sacola',{largura:n('saL'),comprimento:n('saC'),micra:n('saM'),densidade:dens('sa'),descontoPct:n('saDes'),quantidade:n('saQ')});set('saPr',r.pesoUnidade?fmt(r.pesoUnidade,2)+' g':'—');set('saRoM',r.pesoQuantidadeKg?fmt(r.pesoQuantidadeKg,3)+' kg':'—');set('saKg',r.unidadesPorKg?fmt(r.unidadesPorKg,0)+' sacos':'—');set('saMil',r.pesoMilKg?fmt(r.pesoMilKg,2)+' kg':'—')}catch(e){apiError(e)}}
  async function calcCu(){try{const r=await dfCalc('custo',{pesoKg:n('cuPeso'),custoKg:n('cuKg'),vendaKg:n('cuVenda'),quantidade:n('cuQtd')||1});set('cuCustoRolo',r.custoUnidade?rs(r.custoUnidade):'—');set('cuVendaRolo',r.vendaUnidade?rs(r.vendaUnidade):'—');set('cuVendaTotal',r.vendaTotal?rs(r.vendaTotal):'—');set('cuCustoTotal',r.custoTotal?rs(r.custoTotal):'—');set('cuLucro',(n('cuPeso')&&n('cuKg')&&n('cuVenda'))?rs(r.lucroTotal||0):'—')}catch(e){apiError(e)}}

  function loadMats(){try{return JSON.parse(localStorage.getItem(MAT_KEY)||'[]')}catch(_){return[]}}
  function saveMats(a){localStorage.setItem(MAT_KEY,JSON.stringify(a));renderMixRows(FO_ROWS);debounce('fo',calcFo,20)}
  function loadForms(){try{return JSON.parse(localStorage.getItem(FORM_KEY)||'[]')}catch(_){return[]}}
  function saveForms(a){localStorage.setItem(FORM_KEY,JSON.stringify(a));renderForms()}
  function materialById(id){return loadMats().find(m=>String(m.id)===String(id))}
  function buildMatOptions(selected=''){const mats=loadMats();let h=mats.length?'<option value="">Selecione o material</option>':'<option value="">Cadastre material primeiro</option>';mats.forEach(m=>{h+='<option value="'+esc(m.id)+'" '+(String(selected)===String(m.id)?'selected':'')+'>'+esc(m.nome)+(m.preco>0?' — '+rs(m.preco)+'/kg':'')+'</option>'});return h}
  function renderMatBatch(){const b=$('matBatch');if(!b)return;b.innerHTML='<div class="formRow"><div class="rowTitle">Novo material</div><div class="grid"><div><label>Nome do material</label><input id="matNome1" placeholder="Ex.: Canela"></div><div><label>Preço por kg opcional</label><input id="matPreco1" inputmode="decimal" placeholder="Ex.: 5,50"></div></div></div>';if($('matSave'))$('matSave').textContent='CADASTRAR MATERIAL';if($('matClearBatch'))$('matClearBatch').style.display='none'}
  function salvarMateriais(){const ne=$('matNome1'),pe=$('matPreco1'),nome=(ne?.value||'').trim(),preco=parseNum(pe?.value||'');if(!nome){alert('Digite o nome do material.');ne?.focus();return}const mats=loadMats();if(mats.some(m=>safeLower(m.nome)===safeLower(nome))){alert('Esse material já está cadastrado. Não pode cadastrar duas vezes com o mesmo nome.');return}mats.push({id:Date.now()+Math.floor(Math.random()*999),nome,preco});saveMats(mats);if(ne)ne.value='';if(pe)pe.value='';ne?.focus();alert('Material cadastrado. Campo liberado para o próximo material.')}
  function addFoRow(){const sel=$('foAddMat'),pctEl=$('foAddPct'),id=sel?.value||'',pct=parseNum(pctEl?.value||'');if(!id){alert('Escolha um material.');return}if(!(pct>0)){alert('Digite a porcentagem do material.');return}if(FO_ROWS.some(r=>String(r.id)===String(id))){alert('Esse material já foi colocado na formulação.');return}if(FO_ROWS.length>=8){alert('Limite de 8 materiais nesta formulação.');return}const m=materialById(id);FO_ROWS.push({id,nome:m?.nome||'',preco:+m?.preco||0,pct});if(sel)sel.value='';if(pctEl)pctEl.value='';renderMixList();debounce('fo',calcFo,20)}
  function renderMixRows(savedRows=[]){FO_ROWS=(savedRows||[]).map(r=>{const m=materialById(r.id)||r;return{id:String(r.id||''),nome:m.nome||r.nome||'',preco:+m.preco||+r.preco||0,pct:+r.pct||0}}).filter(r=>r.id&&r.pct>0);const b=$('foMixRows');if(!b)return;b.innerHTML='<div class="formRow"><div class="rowTitle">Adicionar na formulação</div><div class="grid"><div><label>Material</label><select id="foAddMat">'+buildMatOptions()+'</select></div><div><label>Porcentagem %</label><input id="foAddPct" inputmode="decimal" placeholder="Ex.: 60"></div></div><button id="foAddRow" class="calcBtn" type="button">ADICIONAR NA FORMULAÇÃO</button></div><div id="foMixList"></div>';$('foAddRow')?.addEventListener('click',addFoRow);$('foAddPct')?.addEventListener('keydown',e=>{if(e.key==='Enter')addFoRow()});$('foMixList')?.addEventListener('click',ev=>{const i=ev.target?.dataset?.remrow;if(i!==undefined){FO_ROWS.splice(+i,1);renderMixList();debounce('fo',calcFo,20)}});renderMixList()}
  function renderMixList(){const b=$('foMixList');if(!b)return;if(!FO_ROWS.length){b.innerHTML="<div class='formNote'>Nenhum material adicionado na formulação ainda.</div>";return}const items=Array.isArray(LAST_FO.itens)?LAST_FO.itens:[];b.innerHTML=FO_ROWS.map((r,i)=>{const m=materialById(r.id)||r,sv=items[i]||{};return '<div class="savedItem"><b>'+esc(m.nome||r.nome)+'</b><div class="formNote">'+fmt(+r.pct||0,2)+'%'+(sv.kg?' = '+fmt(sv.kg,3)+' kg':'')+(sv.custo?' • '+rs(sv.custo):'')+'</div><div class="savedBtns"><button class="delBtn" type="button" data-remrow="'+i+'">REMOVER</button></div></div>'}).join('')}
  function getFoRows(){return FO_ROWS.slice()}
  async function calcFo(){try{const total=n('foTotal'),rows=getFoRows().map(r=>({pct:+r.pct||0,precoKg:+(materialById(r.id)?.preco??r.preco)||0})),r=await dfCalc('formulacao',{totalKg:total,rows});LAST_FO=r;renderMixList();set('foTotPct',r.totalPct?fmt(r.totalPct,2)+'%':'—');set('foTotKg',r.somaKg?fmt(r.somaKg,3)+' kg':'—');set('foCustoTotal',r.custoTotal?rs(r.custoTotal):'—');set('foCustoKg',r.custoKgFinal?rs(r.custoKgFinal)+'/kg':'—');const st=$('foStatus'),d=Number(r.diferencaPara100)||0;if(st){if(Math.abs(d)<=0.05&&Number(r.totalPct)>0){st.textContent='FORMULAÇÃO FECHADA 100% ✅';st.className='midRes ok'}else if(d>0){st.textContent='FALTAM '+fmt(d,2)+'% PARA FECHAR ⚠️';st.className='midRes warn'}else{st.textContent='PASSOU '+fmt(Math.abs(d),2)+'% DO LIMITE ❌';st.className='midRes bad'}}return r}catch(e){apiError(e);return{}}}
  async function salvarFormula(){const nome=($('foNome')?.value||'').trim()||'Formulação',total=n('foTotal'),rows=getFoRows().filter(r=>r.id&&r.pct>0);if(!total){alert('Digite quantos kg quer fazer.');return}if(!rows.length){alert('Escolha pelo menos 1 material.');return}const r=await calcFo();const d=Number(r.diferencaPara100)||0;if(Math.abs(d)>0.05&&!confirm('A formulação não fechou 100%. Salvar mesmo assim?'))return;const rec={id:Date.now(),nome,total,rows,custo:Number(r.custoTotal)||0,custoKg:Number(r.custoKgFinal)||0,criado:new Date().toISOString()};const a=loadForms();a.unshift(rec);saveForms(a);alert('Formulação salva.')}
  function renderForms(){const b=$('foSaved'),a=loadForms();if(!b)return;if(!a.length){b.innerHTML="<div class='formNote'>Nenhuma formulação salva ainda.</div>";return}b.innerHTML=a.map(f=>'<div class="savedItem"><b>'+esc(f.nome)+'</b><div class="formNote">'+fmt(f.total||0,2)+' kg • '+((f.rows||[]).length)+' materiais • '+(f.custo?rs(f.custo):'sem custo')+'</div><div class="savedBtns"><button class="miniBtn" data-openform="'+f.id+'">ABRIR</button><button class="miniBtn" data-dupform="'+f.id+'">DUPLICAR</button><button class="delBtn" data-delform="'+f.id+'">EXCLUIR</button></div></div>').join('')}
  function abrirFormula(f,dup=false){if(!f)return;if($('foNome'))$('foNome').value=dup?(f.nome+' cópia'):f.nome;if($('foTotal'))$('foTotal').value=String(f.total||'').replace('.',',');renderMixRows(f.rows||[]);debounce('fo',calcFo,20);show('fo')}
  function initFormula(){renderMatBatch();renderMixRows();renderForms();$('matSave')?.addEventListener('click',salvarMateriais);$('matNome1')?.addEventListener('keydown',e=>{if(e.key==='Enter')salvarMateriais()});$('matPreco1')?.addEventListener('keydown',e=>{if(e.key==='Enter')salvarMateriais()});$('foTotal')?.addEventListener('input',()=>debounce('fo',calcFo));$('foSave')?.addEventListener('click',salvarFormula);$('foSaved')?.addEventListener('click',ev=>{const id=ev.target.dataset.openform||ev.target.dataset.dupform||ev.target.dataset.delform;if(!id)return;let forms=loadForms(),f=forms.find(x=>String(x.id)===String(id));if(ev.target.dataset.delform){if(confirm('Excluir esta formulação?'))saveForms(forms.filter(x=>String(x.id)!==String(id)));return}if(ev.target.dataset.dupform){const cp={...f,id:Date.now(),nome:(f.nome||'Formulação')+' cópia',criado:new Date().toISOString()};forms.unshift(cp);saveForms(forms);return}abrirFormula(f,false)})}

  function hero(p){const H={ex:['DF EXTRUSOR PRO','CALCULADORA DE EXTRUSÃO • PESO POR METRO • MICRA • DENSIDADE'],sa:['DF EXTRUSOR PRO','CALCULADORA DE SACOLAS • MICRA = PAREDE DUPLA • CÁLCULO AUTOMÁTICO'],cu:['DF EXTRUSOR PRO','CALCULADORA DE CUSTOS • CUSTO • VENDA • LUCRO POR ROLO'],fo:['DF EXTRUSOR PRO','FORMULAÇÃO • MATERIAIS • PORCENTAGEM • CUSTO POR KG']};const v=H[p]||H.ex;set('heroTitle',v[0]);set('heroSub',v[1])}
  function isDev(){return localStorage.getItem(DEV_KEY)==='1'||localStorage.getItem('df_formula_dev')==='1'}
  function show(p){for(const x of ['ex','sa','cu','fo']){const pg=$('pg'+x[0].toUpperCase()+x.slice(1)),bt=$('bt'+x[0].toUpperCase()+x.slice(1));if(pg)pg.classList.toggle('on',x===p);if(bt)bt.classList.toggle('on',x===p)}history.replaceState(null,'',p==='ex'?'./':p==='sa'?'./#sacolas':p==='cu'?'./#custo':'./#formulacao');hero(p);scrollTo(0,0)}

  function bind(){
    window.$=$;window.parseNum=parseNum;window.n=n;window.fmt=fmt;window.rs=rs;window.set=set;window.deviceId=deviceId;window.dfMsg=dfMsg;window.dfLocked=dfLocked;window.dfUnlocked=dfUnlocked;window.dfLicenseAuthLogin=dfLicenseAuthLogin;window.dfCalc=dfCalc;window.dens=dens;window.toggleManual=toggleManual;window.pesoMetroIdeal=pesoMetroIdeal;window.calcEx=calcEx;window.calcCor=calcCor;window.calcProd=calcProd;window.calcSa=calcSa;window.calcCu=calcCu;window.loadMats=loadMats;window.saveMats=saveMats;window.loadForms=loadForms;window.saveForms=saveForms;window.materialById=materialById;window.renderMixRows=renderMixRows;window.getFoRows=getFoRows;window.calcFo=calcFo;window.salvarFormula=salvarFormula;window.renderForms=renderForms;window.abrirFormula=abrirFormula;window.show=show;
    if($('licenseDevice'))$('licenseDevice').textContent='ID deste aparelho: '+deviceId();
    const inp=$('licenseKey'),btn=$('licenseBtn');
    btn?.addEventListener('click',()=>{const k=(inp?.value||'').trim();if(!k)return dfMsg('Digite sua licença.');dfLicenseAuthLogin(k)});
    inp?.addEventListener('keydown',e=>{if(e.key==='Enter')btn?.click()});
    const saved=localStorage.getItem(LICENSE_KEY),savedAccess=localStorage.getItem(ACCESS_KEY);if(saved&&inp){inp.value=saved;dfLicenseAuthLogin(saved,true)}else if(savedAccess)dfUnlocked();else dfLocked();
    ['exL','exM','exP','exDm'].forEach(id=>$(id)?.addEventListener('input',()=>debounce('ex',calcEx)));$('exDs')?.addEventListener('change',()=>debounce('ex',calcEx));
    ['exCorMasA','exCorArA','exCorPuxA'].forEach(id=>$(id)?.addEventListener('input',()=>debounce('cor',calcCor)));$('btnCorPux')?.addEventListener('click',calcCor);$('btnCorMas')?.addEventListener('click',calcCor);
    ['exProdMas','exProdPux','exProdAr','exProdPerc'].forEach(id=>$(id)?.addEventListener('input',()=>debounce('prod',calcProd)));$('btnProd')?.addEventListener('click',calcProd);
    ['saL','saC','saM','saQ','saDes','saDm'].forEach(id=>$(id)?.addEventListener('input',()=>debounce('sa',calcSa)));$('saDs')?.addEventListener('change',()=>debounce('sa',calcSa));
    ['cuPeso','cuKg','cuVenda','cuQtd'].forEach(id=>$(id)?.addEventListener('input',()=>debounce('cu',calcCu)));
    initFormula();
    const hash=location.hash;if(hash==='#sacolas')show('sa');else if(hash==='#custo')show('cu');else if(hash==='#formulacao')show('fo');else show('ex');
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
